# @package _global_
defaults:
  - override /general: fomaml_test

fomaml:
  #general
  env_name: "AntGravity-v1"
  seed: 42
  exp_details: ""

  #experiment data
  task_data: "mbmrl_torch/configurations/task_config/task_stats/AntGravity"
  model_data: "mbmrl_torch/configurations/trained_models/AntGravity_FOMAML.pt"

  #Model Parameters - Online Model Adaption
  epoch: 50
  learning_rate: 0.003
  minibatch_size: 32
  ensemble: 1

  #online adaption (meta testing)
  iterations: 4
  sample_new_task_after_n_iter: 1
  episode_steps: 500
  m_observations: 30
  reset_during_online_adaption: False
  reset_after_x_steps: 500 
  record_video: False #make video of online adaption

  # Parameters of MPC Controller - Random Action Sampling
  controller_type: "mpc"
  mpc_type: "anchor"
  horizon: 10
  lb: -1
  ub: 1
  popsize: 4096
  discount: 0.99

  #Parameters of MPC Controller - CEM Action Sampling
  use_CEM: False
  elites: 0.01
  alpha: 0.000001
  cem_iter: 4

#python3 mbmrl_torch/launcher/run.py +fomaml/stored_configs=test_mpc_anchor_ant_gravity