# MOST OF THE BELOW PARAMS WILL BE OVERWRITTEN BY STORED_CONFIGS!
#generel
wandb_entity: null
env_name: "AntGravity-v1"
seed: 42
exp_details: ""

#experiment data
task_data: null
model_data: null

#Environment, data storage, experiment results storage
result_dir: "mbmrl_torch/experiments/train_test_FAMLE"
model_data_dir: "mbmrl_torch/experiments/train_test_FAMLE"
task_data_dir: "mbmrl_torch/experiments/train_test_FAMLE"
model_name: "meta_dynamics_model_FAMLE"

#tasks settings and data collection
load_task_presets: True
collection_policy: null
episode_length: 10
rollouts: 10
n_tasks_distribution: null
reset_env_when_done: True

#Model Parameters - Offline Meta Learning
hidden_layers: [512,512,512]
hidden_activation: "leakyrelu"
embedding_size: 6
cuda: True
output_limit: null
dropout: 0.0

#Meta Learning Parameters: FAMLE
meta_iter: 100000
meta_iter_reward: 100
meta_step: 2.2
lr_schedule: True
inner_iter: 48
inner_step: 0.003
meta_batch_size: 32
inner_sample_size: 500
meta_train_test_split: 0.8
save_meta_model: True

#Model Parameters - Online Model Adaption
epoch: 97
learning_rate: 0.0005
minibatch_size: 32
ensemble: 1
record_video: False

#online adaption (meta testing)

iterations: 4
sample_new_task_after_n_iter: 1
episode_steps: 500
m_observations: 19
adapt_based_on: "dynamics" 
reset_during_online_adaption: False
reset_after_x_steps: 500

#FAMLE online adaption
sample_model: False
beta: 0.7
num_embeddings: 0
log_additional_data: False

# Parameters of Controller
controller_type: "mpc"
mpc_type: "normal"
horizon: 14
lb: -1
ub: 1
popsize: 8192
discount: 1.0

# Parameters of MPC Controller - CEM
use_CEM: False
elites: 0.1
alpha: 0.1
cem_iter: 4

#parameters that will we adjusted automatically / DON NOT CHANGE!
#general
exp_name: ""
exp_resdir: ""
#training
action_dim: 1
dim_in: 4 
dim_out: 2
dim_out_reward: 1
#controller 
sol_dim: 20
state_dim: 0